### PR TITLE
Complete_mobile_version is the new branch made to satisfy the current project's requirement

### PR DESCRIPTION
**Pull request by Bestbynature**
All checks passed successfuly.

### CODE REVIEW

**Review by vickymarz — CHANGES_REQUESTED** [review]
Hi @Bestbynature, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## ❌ Invalid Code Review Request

You have submitted a project that does not have a descriptive pull request summary. Kindly highlight the features you implemented in your project. You can use bullet points.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Bestbynature** [comment]
Hi @vickymarz 

I don't think this review is fair at all. This is just my third day into this programme. Am I expected to begin to write like someone who has been doing this for months? I have been submitting pull requests since Monday but no reviewer has rejected the request on the basis of "incorrect description". 

I would really have appreciated a clue or hint as to what you are expecting and there are just two reviews left... How will I cope with just two reviews left when the first one was not utilised properly.

**Comment by vickymarz** [comment]
@Bestbynature, I dont understand your concern tho. I only invalidated your review because your pull request summary was not descriptive. I didn't seem to know what changes you added to your project as it was not summarized in the pull request summary. 

Invalidation does not reduce your number of reviews so you can still submit again

**Comment by Bestbynature** [comment]
Hi @vickymarz 

I now understand the meaning of invalidating the request and I am so pleased to rewrite the pull request's description as you've suggested. I also noticed that you wrote an article on pull requests. I will do well for myself to check it out during the day tomorrow. 
My only concern before

**Pull request closed without merging**
